# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
